import { NextRequest, NextResponse } from "next/server";
import { getAuthSession } from "@/lib/supabase/auth";
import prisma from "@/lib/prisma";

// GET - Fetch user's media content
export async function GET(request: NextRequest) {
  try {
    const session = await getAuthSession();

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const type = searchParams.get("type");

    const mediaContents = await prisma.mediaContent.findMany({
      where: {
        userId: session.user.id,
        ...(type && { type: type as "YOUTUBE" | "PODCAST" | "AUDIO" | "VIDEO" }),
      },
      include: {
        Chapter: {
          orderBy: { order: "asc" },
        },
        _count: {
          select: { MediaNote: true, MediaBookmark: true },
        },
      },
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json(mediaContents);
  } catch (error) {
    console.error("Error fetching media:", error);
    return NextResponse.json(
      { error: "Failed to fetch media" },
      { status: 500 }
    );
  }
}

// POST - Add new media content
export async function POST(request: NextRequest) {
  try {
    const session = await getAuthSession();

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { type, title, url, description, duration, sourceId } = body;

    if (!type || !title || !url) {
      return NextResponse.json(
        { error: "type, title, and url are required" },
        { status: 400 }
      );
    }

    // Extract YouTube chapters if applicable
    let chapters: { title: string; startTime: number }[] = [];
    if (type === "YOUTUBE") {
      chapters = await extractYouTubeChapters(url);
    }

    const mediaContent = await prisma.mediaContent.create({
      data: {
        id: crypto.randomUUID(),
        userId: session.user.id,
        type,
        title,
        url,
        description: description || null,
        duration: duration || null,
        sourceId: sourceId || null,
        updatedAt: new Date(),
        Chapter: {
          create: chapters.map((ch, index) => ({
            id: crypto.randomUUID(),
            title: ch.title,
            startTime: ch.startTime,
            order: index,
            isAutoGenerated: true,
            updatedAt: new Date(),
          })),
        },
      },
      include: {
        Chapter: {
          orderBy: { order: "asc" },
        },
      },
    });

    return NextResponse.json({
      message: "Media added successfully",
      media: mediaContent,
    });
  } catch (error) {
    console.error("Error adding media:", error);
    return NextResponse.json(
      { error: "Failed to add media" },
      { status: 500 }
    );
  }
}

// Helper to extract YouTube chapters from video description
async function extractYouTubeChapters(
  url: string
): Promise<{ title: string; startTime: number }[]> {
  try {
    // Extract video ID from URL
    const videoIdMatch = url.match(
      /(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))([^&\n?#]+)/
    );
    if (!videoIdMatch) return [];

    const videoId = videoIdMatch[1];

    // Fetch video info from YouTube oEmbed API (limited info)
    // For full chapter extraction, you'd need YouTube Data API
    // This is a simplified version that just returns empty for now
    // In production, use YouTube Data API v3

    return [];
  } catch (error) {
    console.error("Error extracting YouTube chapters:", error);
    return [];
  }
}
